version: '3'

services:
  source_postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: source_db
    volumes:
      - ./source_db_init/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  destination_postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: destination_db
    
  elt:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - source_postgres
      - destination_postgres
    networks:
      - elt_network
    command: ["python", "elt_script.py"]

networks:
  elt_network:
    driver: bridge